#!/bin/bash
# daily_synthesis.sh — Anti-Menguap Automated Cron
#
# Tiap hari pukul 22:00 WIB (15:00 UTC), synthesize hari ini:
# - git log hari ini
# - Research notes baru
# - Tail FOUNDER_JOURNAL last entries
# - Tail LIVING_LOG last events
#
# Output: 1 paragraph "today's state" → docs/DAILY_SYNTHESIS_<date>.md
#
# Tomorrow session start: agent baca file ini, bukan re-read 309 notes.
#
# Pattern lahir dari diskusi 2026-04-30 evening:
# Bos: "semua bisa di iterasi dan di sintesis, cognitive tiap harinya"
#
# Reference: research note 308 (Sprint Cowork Skills + Daily Synthesis)

set -u
REPO="${REPO:-/opt/sidix}"
cd "$REPO"

DATE=$(date +%Y-%m-%d)
HOUR_WIB=$(TZ=Asia/Jakarta date +%H)
OUTPUT_FILE="docs/DAILY_SYNTHESIS_${DATE}.md"
LOG_FILE="${REPO}/.data/daily_synthesis.log"

mkdir -p "$(dirname "$LOG_FILE")"
mkdir -p "${REPO}/docs"

echo "[$(date -Iseconds)] daily_synthesis start" >> "$LOG_FILE"

# Skip kalau sudah ada synthesis hari ini (idempotent)
if [ -f "$OUTPUT_FILE" ] && [ "$(wc -c < "$OUTPUT_FILE")" -gt 200 ]; then
  echo "[$(date -Iseconds)] $OUTPUT_FILE already exists, skip" >> "$LOG_FILE"
  exit 0
fi

# Gather data hari ini
COMMITS_TODAY=$(git log --since="midnight" --oneline 2>/dev/null | head -30)
COMMIT_COUNT=$(echo "$COMMITS_TODAY" | grep -c . || echo 0)
NOTES_TODAY=$(find brain/public/research_notes -name "*.md" -newermt "$DATE 00:00" 2>/dev/null | head -10)
JOURNAL_TAIL=$(tail -80 docs/FOUNDER_JOURNAL.md 2>/dev/null | head -60)
LIVING_TAIL=$(tail -40 docs/LIVING_LOG.md 2>/dev/null | head -30)
BACKLOG_STATE=$(grep -E "^### Sprint|^## " docs/SIDIX_BACKLOG.md 2>/dev/null | head -25)

# Build prompt untuk SIDIX brain
PROMPT="Synthesize aktivitas SIDIX hari ini ($DATE) jadi 1 paragraf concise (max 200 kata).

DATA HARI INI:
- Git commits ($COMMIT_COUNT total):
$COMMITS_TODAY

- Research notes baru: $NOTES_TODAY

- BACKLOG state recent:
$BACKLOG_STATE

- FOUNDER_JOURNAL recent:
$JOURNAL_TAIL

- LIVING_LOG recent:
$LIVING_TAIL

Tulis sebagai paragraf yang akan dibaca agent (Claude/GPT/Gemini) BESOK pagi sebagai briefing — apa yang terjadi hari ini, decision penting, sprint progress, gap visi, dan apa yang next."

# Compose request body (escape JSON)
PAYLOAD=$(python3 -c "
import json, sys
prompt = '''$PROMPT'''
print(json.dumps({'question': prompt[:5000], 'persona': 'OOMAR'}))
" 2>/dev/null)

if [ -z "$PAYLOAD" ]; then
  echo "[$(date -Iseconds)] ERROR: payload empty" >> "$LOG_FILE"
  exit 1
fi

# Hit /agent/chat_holistic (jurus seribu bayangan untuk synthesis)
TS_START=$(date +%s)
RESPONSE=$(curl -s --max-time 240 -X POST http://localhost:8765/agent/chat_holistic \
  -H "Content-Type: application/json" \
  -d "$PAYLOAD" 2>/dev/null)
TS_END=$(date +%s)
ELAPSED=$((TS_END - TS_START))

# Parse answer
SUMMARY=$(echo "$RESPONSE" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
    print(d.get('answer', '(synthesis empty)'))
except Exception as e:
    print(f'(parse error: {e})')
" 2>/dev/null)

# Build output file
cat > "$OUTPUT_FILE" <<EOF
# Daily Synthesis — $DATE

> Auto-generated by SIDIX brain via /agent/chat_holistic (jurus seribu bayangan).
> Tomorrow morning, agent (Claude/GPT/Gemini) yang baca file ini = grounded
> tanpa harus re-read 309 research notes.

**Generated**: $(date -Iseconds) (latency ${ELAPSED}s)
**Commits today**: $COMMIT_COUNT
**Method**: Multi-source orchestrator + neutral synthesizer (Sprint Α)

---

## Today's State

$SUMMARY

---

## Quick Stats

- Total commits: $COMMIT_COUNT
- Last 5 commits:
$(echo "$COMMITS_TODAY" | head -5 | sed 's/^/  - /')

- New research notes:
$(echo "$NOTES_TODAY" | sed 's/^/  - /')

---

## For Agent Reading This Tomorrow

Pesan untuk agent berikutnya yang baca file ini di sesi baru:

1. Anggap ini briefing pagi tentang state SIDIX hari ini.
2. Output state read protocol tetap mandatory (per CLAUDE.md SESSION START PROTOCOL).
3. Sprint berikutnya queued: cek docs/SIDIX_BACKLOG.md.
4. Bos eksplisit delegate engineering authority — kamu yang decide teknis.
5. Anti-menguap: catat ide bos verbatim ke FOUNDER_IDEA_LOG saat dia kasih visi baru.

EOF

echo "[$(date -Iseconds)] daily_synthesis DONE elapsed=${ELAPSED}s output=$OUTPUT_FILE" >> "$LOG_FILE"

# Auto-commit kalau ada git config yang bener (optional, default off untuk safety)
if [ "${SIDIX_AUTO_COMMIT_SYNTHESIS:-0}" = "1" ]; then
  git add "$OUTPUT_FILE"
  git commit -m "synthesis(daily): $DATE auto-generated" --no-verify 2>&1 | tail -2 >> "$LOG_FILE"
  # Push optional, default off
  if [ "${SIDIX_AUTO_PUSH_SYNTHESIS:-0}" = "1" ]; then
    git push origin "$(git branch --show-current)" 2>&1 | tail -2 >> "$LOG_FILE"
  fi
fi

exit 0
